#include <GL/glut.h>
#include <math.h>

// DIMENSIONS & AESTHETICS

	//WINDOW HEIGHT WIDTH
	//PADDLE HEIGHT WIDTH
	//BALL HEIGHT WIDTH

// FUNCTIONS
	//BALL SPEED
	//BALL BOUNCE
	//MOVEMENT PADDLE A & PADDLE B

